import { Header } from '@app/components';
import { NextAuthProvider } from '@app/components/AuthProvider';
import { fonts } from '@libs/config';
import { ThemeProvider, ToastProvider } from '@libs/ui';
import './global.css';

export const metadata = {
  title: 'Welcome to clinicspots',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${fonts.inter.className}`}>
        <ThemeProvider>
          <ToastProvider>
            <NextAuthProvider>
              <div className="min-h-screen">
                <Header />
                <div style={{ marginTop: 64 }}>{children}</div>
              </div>
            </NextAuthProvider>
          </ToastProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
