import { fonts } from '@grow/config';
import { ThemeProvider } from '@grow/ui';
import { Header, NextAuthProvider } from '../components';
import './global.css';

export const metadata = {
  title: 'Welcome to grow',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${fonts.inter.className}`}>
        <ThemeProvider>
          <NextAuthProvider>
            <div className="min-h-screen">
              <Header />
              {children}
            </div>
          </NextAuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
